#!/bin/bash
# DEPLOYMENT INSTRUCTIONS FOR 000WEBHOST
# Follow these exact steps to go live in 10 minutes!

echo "==================================="
echo "ASTROQUIZ 2026 - LIVE DEPLOYMENT"
echo "==================================="
echo ""
echo "STEP 1: CREATE FREE HOSTING ACCOUNT"
echo "-----------------------------------"
echo "1. Open browser: https://www.000webhost.com"
echo "2. Click 'Sign Up Free'"
echo "3. Enter:"
echo "   - Email: your-email@gmail.com"
echo "   - Password: (strong password)"
echo "4. Verify email (check inbox)"
echo "5. Click verification link"
echo ""
echo "STEP 2: CREATE WEBSITE"
echo "-----------------------------------"
echo "1. Login to 000webhost dashboard"
echo "2. Click 'Create New Site'"
echo "3. Choose subdomain:"
echo "   Example: astroquiz2026.000webhostapp.com"
echo "   (or your preferred name)"
echo "4. Set password for website"
echo "5. Click 'Create'"
echo "6. Wait 2-3 minutes (setup time)"
echo ""
echo "STEP 3: UPLOAD FILES"
echo "-----------------------------------"
echo "1. Click 'File Manager' in dashboard"
echo "2. Navigate to 'public_html' folder"
echo "3. DELETE the existing 'default.php' file"
echo "4. Click 'Upload Files' button (top right)"
echo "5. Select ALL files from astro-quiz-2026 folder:"
echo "   - index.html"
echo "   - quizzes/ (folder)"
echo "   - css/ (folder)"
echo "   - js/ (folder)"
echo "   - api/ (folder)"
echo "   - includes/ (folder)"
echo "   - .htaccess"
echo "   - robots.txt"
echo "   - sitemap.xml"
echo "6. Wait for upload to complete (1-2 min)"
echo ""
echo "STEP 4: TEST YOUR SITE"
echo "-----------------------------------"
echo "1. Open browser"
echo "2. Visit: https://your-subdomain.000webhostapp.com"
echo "3. Your site should load!"
echo "4. Test 1 quiz end-to-end"
echo "5. Check on mobile too"
echo ""
echo "STEP 5: SHARE & GO VIRAL!"
echo "-----------------------------------"
echo "1. Copy your URL"
echo "2. Share on WhatsApp (10 friends)"
echo "3. Post on Instagram/X"
echo "4. Watch traffic grow!"
echo ""
echo "==================================="
echo "SITE LIVE IN 10 MINUTES! 🚀"
echo "==================================="